apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-qgcr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-qgcr
    app.kubernetes.io/part-of: test-app-uupj
  name: test-component-qgcr
  namespace: build-e2e-emib-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-qgcr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-qgcr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:a4169304fad45eb08ce351e2e3026f126623ffa496ac12c86039da47715e37e8
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
