apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-qgcr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-qgcr
    app.kubernetes.io/part-of: test-app-uupj
  name: test-component-qgcr
  namespace: build-e2e-emib-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-qgcr
status:
  loadBalancer: {}
